<a href="https://colab.research.google.com/github/osamaahmad291/Machine_learning/blob/main/Transfer_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf

# Create a Constant op that produces a 1x2 matrix.  The op is
# added as a node to the default graph.
#
# The value returned by the constructor represents the output
# of the Constant op.
matrix1 = tf.constant([[3., 3.]])

# Create another Constant that produces a 2x1 matrix.
matrix2 = tf.constant([[2.],[2.]])

# Create a Matmul op that takes 'matrix1' and 'matrix2' as inputs.
# The returned value, 'product', represents the result of the matrix
# multiplication.
product = tf.matmul(matrix1, matrix2)
print(product)
print(float(product))


tf.Tensor([[3. 3.]], shape=(1, 2), dtype=float32)
tf.Tensor(
[[2.]
 [2.]], shape=(2, 1), dtype=float32)
tf.Tensor([[12.]], shape=(1, 1), dtype=float32)
12.0
tf.Tensor(
[[6. 6.]
 [6. 6.]], shape=(2, 2), dtype=float32)


In [4]:
import tensorflow as tf

x = tf.Variable([1.0, 2.0])
a = tf.constant([3.0, 3.0])

# Add an op to subtract 'a' from 'x'.  Run it and print the result
sub = tf.subtract(x, a)
print(sub)
print(sub.numpy())
# ==> [-2. -1.]

tf.Tensor([-2. -1.], shape=(2,), dtype=float32)
[-2. -1.]


In [5]:
x.assign([4.0, 6.0])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([4., 6.], dtype=float32)>

In [6]:
sub = tf.subtract(x, a)
print(sub)
print(sub.numpy())

tf.Tensor([1. 3.], shape=(2,), dtype=float32)
[1. 3.]


In [1]:

import pandas as pd
import io
import requests
import numpy as np
from sklearn import metrics
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.callbacks import EarlyStopping

df = pd.read_csv(
    "https://data.heatonresearch.com/data/t81-558/iris.csv", 
    na_values=['NA', '?'])

# Convert to numpy - Classification
x = df[['sepal_l', 'sepal_w', 'petal_l', 'petal_w']].values
dummies = pd.get_dummies(df['species']) # Classification
species = dummies.columns
y = dummies.values


# Build neural network
model = Sequential()
model.add(Dense(50, input_dim=x.shape[1], activation='relu')) # Hidden 1
model.add(Dense(25, activation='relu')) # Hidden 2
model.add(Dense(y.shape[1],activation='softmax')) # Output

model.compile(loss='categorical_crossentropy', optimizer='adam')
model.fit(x,y,verbose=2,epochs=100)

Epoch 1/100
5/5 - 3s - loss: 1.1286
Epoch 2/100
5/5 - 0s - loss: 0.9081
Epoch 3/100
5/5 - 0s - loss: 0.8374
Epoch 4/100
5/5 - 0s - loss: 0.7867
Epoch 5/100
5/5 - 0s - loss: 0.7378
Epoch 6/100
5/5 - 0s - loss: 0.6879
Epoch 7/100
5/5 - 0s - loss: 0.6474
Epoch 8/100
5/5 - 0s - loss: 0.6090
Epoch 9/100
5/5 - 0s - loss: 0.5732
Epoch 10/100
5/5 - 0s - loss: 0.5397
Epoch 11/100
5/5 - 0s - loss: 0.5104
Epoch 12/100
5/5 - 0s - loss: 0.4849
Epoch 13/100
5/5 - 0s - loss: 0.4645
Epoch 14/100
5/5 - 0s - loss: 0.4446
Epoch 15/100
5/5 - 0s - loss: 0.4277
Epoch 16/100
5/5 - 0s - loss: 0.4099
Epoch 17/100
5/5 - 0s - loss: 0.3951
Epoch 18/100
5/5 - 0s - loss: 0.3840
Epoch 19/100
5/5 - 0s - loss: 0.3712
Epoch 20/100
5/5 - 0s - loss: 0.3595
Epoch 21/100
5/5 - 0s - loss: 0.3489
Epoch 22/100
5/5 - 0s - loss: 0.3383
Epoch 23/100
5/5 - 0s - loss: 0.3295
Epoch 24/100
5/5 - 0s - loss: 0.3203
Epoch 25/100
5/5 - 0s - loss: 0.3109
Epoch 26/100
5/5 - 0s - loss: 0.3025
Epoch 27/100
5/5 - 0s - loss: 0.2948
Epoch 28/1

In [2]:

from sklearn.metrics import accuracy_score
pred = model.predict(x)
predict_classes = np.argmax(pred,axis=1)
expected_classes = np.argmax(y,axis=1)
correct = accuracy_score(expected_classes,predict_classes)
print(f"Training Accuracy: {correct}")

Training Accuracy: 0.98


In [3]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 50)                250       
_________________________________________________________________
dense_1 (Dense)              (None, 25)                1275      
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 78        
Total params: 1,603
Trainable params: 1,603
Non-trainable params: 0
_________________________________________________________________


In [4]:
model2 = Sequential()
for layer in model.layers:
    model2.add(layer)
model2.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 50)                250       
_________________________________________________________________
dense_1 (Dense)              (None, 25)                1275      
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 78        
Total params: 1,603
Trainable params: 1,603
Non-trainable params: 0
_________________________________________________________________


In [6]:
from sklearn.metrics import accuracy_score
pred = model2.predict(x)
predict_classes = np.argmax(pred,axis=1)
expected_classes = np.argmax(y,axis=1)
correct = accuracy_score(expected_classes,predict_classes)
print(f"Training Accuracy: {correct}")

Training Accuracy: 0.98


In [7]:
model3 = Sequential()
for i in range(2):
    layer = model.layers[i]
    layer.trainable = False
    model3.add(layer)
model3.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 50)                250       
_________________________________________________________________
dense_1 (Dense)              (None, 25)                1275      
Total params: 1,525
Trainable params: 0
Non-trainable params: 1,525
_________________________________________________________________


In [8]:
model3.add(Dense(4,activation='softmax')) # Output

model3.compile(loss='categorical_crossentropy', optimizer='adam')
model3.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 50)                250       
_________________________________________________________________
dense_1 (Dense)              (None, 25)                1275      
_________________________________________________________________
dense_3 (Dense)              (None, 4)                 104       
Total params: 1,629
Trainable params: 104
Non-trainable params: 1,525
_________________________________________________________________
